import LocalizedStrings from 'localized-strings';

export default new LocalizedStrings({
  en:{
    app_name: "Particulate Matter App",
    action_successful: "Action completed successfully",
    sensor_added_successfully: "Sensor added successfully!",
    error_please_try_again: "Error! Please try again.",
    sensor_favourized: "Sensor favourized successfully!",
    favourization_failed_try_again: "Favourization failed! Please try again.",
    changings_saved: "Changings saved successfully!",
    changings_save_failed: "The changings could not be saved! Please try again.",
    sensor_removed_successfully: "Removed sensor successfully!",
    sensor_removal_failed: "Sensor removal failed! Please try again.",
    add_sensor: "Add sensor",
    unknown_sensor: "Unknown sensor",
    sensors: "sensors",
    our_homepage: "Our homepage",
    download_android_app: "Download android app",
    info: "Info",
    add_sensor_to_favourites: "Add sensor to favourites",
    display_name: "Display name",
    chip_id: "Chip id",
    cancel: "Cancel",
    ok: "OK",
    save: "Save",
    back: "Back",
    next: "Next",
    skip: "Skip",
    add_favourite: "Add favourite",
    error_add_sensor: "You entered a wrong chip id or the option 'Send to Feinstaub-App' is not enabled in the configuration of your sensor. After it is enabled, it can last up to 10 minutes until our server receives data from the sensor.",
    enter_chip_id: "Enter chip id",
    enter_chip_id_instruction: "Please enter the chip id of your sensor below. You can find the id in the configuration of your sensor. If you still not find the chip id, you can check out the entry on our <a href='https://mrgames13.jimdo.com/feinstaub-app/faq/#6' target='blank'>faq site</a>.",
    enter_base_data: "Enter base data",
    display_name_color_instruction: "Please choose a display name and a color for sensor within the diagrams",
    add_sensor_to_map: "Add sensor to the map",
    add_sensor_to_map_instruction: "To add your sensor to the map, you have to enter the exact location and the mounting height of the sensor <b>over the ground </b>.<br><b>HINT:</b> This values only can be changed afterwards, if you <a href='mailto:mrgames@outlook.de'>send us an email</a>.",
    soon_available: "Soon available",
    latitude: "Latitude",
    longitude: "Longitude",
    mounting_height: "Mounting height (in meters)",
    choose_location: "Choose location of sensor",
    edit_sensor: "Edit sensor",
    remove_sensor: "Remove sensor",
    remove_sensor_message_1: "Do you really want to remove the sensor with the chip id",
    remove_sensor_message_2: "? You could link it again at any time.",
    remove: "Remove",
    pm1: "PM10",
    pm2: "PM2.5",
    temperature: "Temperature",
    humidity: "Humidity",
    pressure: "Pressure",
    show_sensor_details: "Show sensor details",
    show_details: "Show details",
    close_window: "Close window",
    day_before: "Day before",
    day_after: "Day after",
    choose_another_date: "Choose another date",
    diagram: "Diagram",
    data_records: "Data records",
    time_of_day: "Time",
    measurement: "Measurement",
    show_pm1: "Show PM10 curve",
    show_pm2: "Show PM2.5 curve",
    show_temperature: "Show temperature curve",
    show_humidity: "Show humidity curve",
    show_pressure: "Show pressure curve",
    show_time: "Show measurement time",
    hide_dots: "Hide dots",
    enable_soft_curve: "Enable soft curve",
    enable_curve_smoothing: "Enable curve smoothing",
    zoom_of_diagram_: "Zoom of the diagram:",
    no_data: "No data existing",
    loading: "Loading ...",
    sensor_details: "Sensor details",
    public: "Public",
    online_since: "Online since",
    link_with_android_app: "Link with android app",
    link_instruction_1: "To synchronize your sensors and your favourites,",
    link_instruction_2: "start the Particulate Matter App.",
    link_instruction_3: "Three dots at the top right corner → 'Web version'.",
    link_instruction_4: "Scan the qr code above.",
    show_measurements: "Show measurements",
    properties: "Properties",
    no_favourites: "No favourites existing yet. To add a favourite, click on a sonsor on the map and select 'Add favourite'.",
    no_own_sensors: "If you have an particulate matter sensor from <a href='https://luftdaten.info/feinstaubsensor-bauen/' target='blank'>www.luftdaten.info</a>, you can link it here. Click on the '+' button in the right bottom corner on the page.",
    favourites: "My favourites",
    own_sensors: "Own sensors",
    loading_address: "Loading address ...",
    unknown_country: "Unknown country",
    unknown_city: "Unknown city",
    delete: "Delete",
    previous_page: "Previous page",
    next_page: "Next page",
  },
  de: {
    app_name: "Feinstaub-App",
    action_successful: "Die Aktion war erfolgreich!",
    sensor_added_successfully: "Sensor erfolgreich hinzugefügt!",
    error_please_try_again: "Fehler! Bitte versuchen Sie es erneut.",
    sensor_favourized: "Der Sensor wurde favorisiert!",
    favourization_failed_try_again: "Favorisieren fehlgeschlagen! Bitte versuchen Sie es erneut.",
    changings_saved: "Änderungen erfolgreich gespeichert!",
    changings_save_failed: "Die Änderungen konnten nicht gespeichert werden! Bitte versuchen Sie es erneut.",
    sensor_removed_successfully: "Sensor erfolgreich entfernt!",
    sensor_removal_failed: "Entfernen fehlgeschlagen! Bitte versuchen Sie es erneut.",
    add_sensor: "Sensor hinzufügen",
    unknown_sensor: "Unbekannter Sensor",
    sensors: "Sensoren",
    our_homepage: "Unsere Homepage",
    download_android_app: "Android-App herunterladen",
    info: "Info",
    add_sensor_to_favourites: "Sensor zu Favoriten hinzufügen",
    display_name: "Anzeigename",
    chip_id: "Chip-ID",
    cancel: "Abbrechen",
    ok: "OK",
    save: "Speichern",
    back: "Zurück",
    next: "Weiter",
    skip: "Überspringen",
    add_favourite: "Favorit hinzufügen",
    error_add_sensor: "Sie haben entweder die falsche Chip-ID angegeben oder in der Konfiguration Ihres Sensors ist die Option 'Senden an Feinstaub-App' nicht aktiviert. Nachdem die Option aktiviert ist, kann es bis zu 10 Minuten dauern, bis Daten auf dem Server ankommen.",
    enter_chip_id: "Chip-ID angeben",
    enter_chip_id_instruction: "Bitte geben Sie die Chip-ID Ihres Sensors in das Feld unten ein. Sie finden die ID in der Konfiguration Ihres Sensors. Falls Sie die Chip-ID dennoch nicht finden sollten, finden Sie auf unserer <a href='https://mrgames13.jimdo.com/feinstaub-app/faq/#6' target='blank'>FAQ-Seite</a> einen Eintrag.",
    enter_base_data: "Basisdaten angeben",
    display_name_color_instruction: "Bitte vergeben Sie für Ihren Sensor einen Anzeigenamen und bestimmen Sie eine Farbe für den Sensor innerhalb der Diagramme.",
    add_sensor_to_map: "Sensor auf die Karte bringen",
    add_sensor_to_map_instruction: "Um Ihren Sensor auf die Karte zu bekommen, müssen Sie die genaue Position des Sensors und die Montagehöhe <b>über dem Boden</b> angeben.<br/><b>HINWEIS:</b> Diese Daten können später nur noch geändert werden, indem Sie per E-Mail mit uns in <a href='mailto:mrgames@outlook.de'>Kontakt</a> treten.",
    soon_available: "Bald verfügbar",
    latitude: "Längengrad",
    longitude: "Breitengrad",
    mounting_height: "Montagehöhe (in Meter)",
    choose_location: "Position des Sensors wählen",
    edit_sensor: "Sensor bearbeiten",
    remove_sensor: "Sensor entfernen",
    remove_sensor_message_1: "Wollen Sie den Sensor mit der Chip-ID",
    remove_sensor_message_2: "wirklich entfernen? Sie können ihn jederzeit wieder verknüpfen.",
    remove: "Entfernen",
    pm1: "PM10",
    pm2: "PM2,5",
    temperature: "Temperatur",
    humidity: "Luftfeuchtigkeit",
    pressure: "Luftdruck",
    show_sensor_details: "Sensordetails anzeigen",
    show_details: "Details anzeigen",
    close_window: "Fenster schließen",
    day_before: "Tag davor",
    day_after: "Tag danach",
    choose_another_date: "Anderes Datum wählen",
    diagram: "Diagramm",
    data_records: "Datensätze",
    time_of_day: "Uhrzeit",
    measurement: "Messwert",
    show_pm1: "PM10-Kurve anzeigen",
    show_pm2: "PM2,5-Kurve anzeigen",
    show_temperature: "Temperatur-Kurve anzeigen",
    show_humidity: "Luftfeuchtigkeit-Kurve anzeigen",
    show_pressure: "Luftdruck-Kurve anzeigen",
    show_time: "Messzeiten einblenden",
    hide_dots: "Punkte ausblenden",
    enable_soft_curve: "Weiche Kurve aktivieren",
    enable_curve_smoothing: "Kurvenglättung aktivieren",
    zoom_of_diagram_: "Zoom des Diagrammes:",
    no_data: "Keine Daten vorhanden",
    loading: "Laden ...",
    sensor_details: "Sensor Details",
    public: "Öffentlich",
    online_since: "Online seit",
    link_with_android_app: "Mit der Android-App verknüpfen",
    link_instruction_1: "Um Ihre Sensoren und Ihre Favouriten aus der App",
    link_instruction_2: "hier anzuzeigen, starten Sie die Feinstaub-App.",
    link_instruction_3: "Drei Punkte oben rechts → 'Web-Version'.",
    link_instruction_4: "Scannen Sie den obigen QR-Code.",
    show_measurements: "Messwerte anzeigen",
    properties: "Eigenschaften",
    no_favourites: "Noch keine Favouriten vorhanden. Um Favoriten hinzuzufügen, tippen Sie auf der Karte auf einen Sensor und wählen Sie 'Favorit hinzufügen'.",
    no_own_sensors: "Falls Sie einen eigenen Feinstaubsensor von <a href='https://luftdaten.info/feinstaubsensor-bauen/' target='blank'>www.luftdaten.info</a> haben, können Sie ihn hier verknüpfen. Klicken Sie auf den '+'-Button ganz unten rechts auf der Seite.",
    favourites: "Meine Favouriten",
    own_sensors: "Meine Sensoren",
    loading_address: "Adresse wird geladen ...",
    unknown_country: "Unbekanntes Land",
    unknown_city: "Unbekannte Stadt",
    delete: "Löschen",
    previous_page: "Vorherige Seite",
    next_page: "Nächste Seite",
  }},
);
